usr/lib/lib*.a
usr/include/*
usr/include/vsip/*
usr/include/vsip/core/*
usr/include/vsip/core/signal/*
usr/include/vsip/core/parallel/*
usr/include/vsip/core/cvsip/*
usr/include/vsip/core/expr/*
usr/include/vsip/core/reductions/*
usr/include/vsip/core/solver/*
usr/include/vsip/core/fft/*
usr/include/vsip/core/mpi/*
usr/include/vsip/opt/*
usr/include/vsip/opt/signal/*
usr/include/vsip/opt/sal/*
usr/include/vsip/opt/fftw3/*
usr/include/vsip/opt/pas/*
usr/include/vsip/opt/parallel/*
usr/include/vsip/opt/expr/*
usr/include/vsip/opt/reductions/*
usr/include/vsip/opt/diag/*
usr/include/vsip/opt/simd/*
usr/include/vsip/opt/ipp/*
usr/include/vsip/opt/lapack/*
usr/include/vsip/opt/fft/*
usr/include/vsip_csl/*
usr/include/vsip_csl/output/*
usr/include/vsip_csl/img/*
usr/include/vsip_csl/img/impl/*
usr/include/vsip_csl/stencil/*



